# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: zip repo

on:
  push:
    branches:
    - main

jobs:
  
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: simple-nodejs-main.zip
          
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          repository: scaffolding-repos/ado-scaffolding

      - name: Copy
        uses: canastro/copy-action@0.0.2
        with: 
          source: simple-nodejs-master.zip
          target: public/scaffolding/
          
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          push-branch: 'master'
          commit-message: 'publish new simple-nodejs-main.zip'
          force-add: 'true'
          files: public/scaffolding/simple-nodejs-main.zip 
          name: maye-msft
          email: maye-msft@outlook.com

