# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: zip repo

on:
  push:
    branches:
    - main

jobs:
  
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: ZIP Scaffolding
        run: |
            git clone https://github.com/scaffolding-repos/simple-node
            cd simple-node
            git archive --format=zip origin/main --output=./simple-nodejs-main.zip
            ls -l
            
      - name: Clone ado-scaffolding
        run: |
            git clone https://github.com/scaffolding-repos/ado-scaffolding
            cd ado-scaffolding
            cp ../simple-node/simple-nodejs-main.zip public/scaffolding 
            git add -A
            git commit -m "publish scaffloding by zip"
            
          
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          repository: scaffolding-repos/ado-scaffolding

      - name: Copy
        run: cp simple-node/simple-nodejs-main.zip 
          
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          push-branch: 'master'
          commit-message: 'publish new simple-nodejs-main.zip'
          force-add: 'true'
          files: public/scaffolding/simple-nodejs-main.zip 
          name: maye-msft
          email: maye-msft@outlook.com

